### ISSUE TITLE
TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by camilonova** [django-pci/django-axes#166]
Python 3.5 and Django 1.10 is giving this error:

```
File "/usr/local/lib/python3.5/site-packages/axes/middleware.py", line 9, in __init__
super(FailedLoginMiddleware, self).__init__(*args, **kwargs)
TypeError: object.__init__() takes no parameters
```

@aclark4life can you please take a look?

I've tried to change it but I'm getting `TypeError: 'FailedLoginMiddleware' object is not callable`. Maybe is time to move away from the middleware?

**Comment by aclark4life** [comment]
@camilonova Will do

**Comment by camilonova** [comment]
Thanks

**Comment by camilonova** [comment]
Pretty much

**Comment by aclark4life** [comment]
@camilonova How do you reproduce this? I don't see the issue using the demo project/app I just committed to master …

**Comment by camilonova** [comment]
This is the full stack trace I'm getting:

```
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
web_1        |     fn(*args, **kwargs)
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
web_1        |     handler = self.get_handler(*args, **options)
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
web_1        |     handler = super(Command, self).get_handler(*args, **options)
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
web_1        |     return get_internal_wsgi_application()
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
web_1        |     return import_string(app_path)
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
web_1        |     module = import_module(module_path)
web_1        |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1        |     return _bootstrap._gcd_import(name[level:], package, level)
web_1        |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
web_1        |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
web_1        |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
web_1        |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
web_1        |   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
web_1        |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
web_1        |   File "/code/app/wsgi.py", line 7, in <module>
web_1        |     application = get_wsgi_application()
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
web_1        |     return WSGIHandler()
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
web_1        |     self.load_middleware()
web_1        |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 79, in load_middleware
web_1        |     mw_instance = middleware(handler)
web_1        |   File "/usr/local/lib/python3.5/site-packages/axes/middleware.py", line 9, in __init__
web_1        |     super(FailedLoginMiddleware, self).__init__(*args, **kwargs)
web_1        | TypeError: object.__init__() takes no parameters
```

**Comment by aclark4life** [comment]
@camilonova And you get it with the test project I just committed?

**Comment by camilonova** [comment]
@aclark4life maybe this is it? https://docs.djangoproject.com/en/dev/releases/1.10/#new-style-middleware

**Comment by camilonova** [comment]
Fixed with https://github.com/django-pci/django-axes/commit/730857a1589e02414b8226f6b0d362e3eaaa627a

**Comment by aclark4life** [comment]
Nice. Glad I could help 😄

**Comment by camilonova** [comment]
Thanks :)
